version: '3.6'

services:
  codingchallenge:
    image: coding-challenge
    container_name: coding-challenge-app
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - DB_DEFAULT_HOST=172.17.0.1





