version: '3.6'

services:
  postgres:
    image: postgres
    container_name: coding-challenge-psql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=coding_challenge_usr
      - POSTGRES_PASSWORD=coding_challeng_password
      - POSTGRES_DB=coding_challenge
    volumes:
      - ./docker/psql/:/docker-entrypoint-initdb.d/





