spring:
  application:
    name: "codingchallenge  "
#  jpa:
#    show-sql: false
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  datasource:
#    url: jdbc:postgresql://${DB_DEFAULT_HOST:localhost}:${DB_PORT:5432}/${DB_DEFAULT_DATABASE:${spring.application.name}}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 2

management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: never
      show-components: never

springdoc:
  show-actuator: false
