spring:
  application:
    name: "codingchallenge"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://${DB_DEFAULT_HOST:localhost}:5432/coding_challenge
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      username: coding_challenge_usr
      password: coding_challeng_password

  liquibase:
    change-log: db.changelog/dbchangelog.xml

management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: never
      show-components: never

springdoc:
  show-actuator: false
