spring:
  application:
    name: "codingchallenge"
    baseUrl: "www.example.com"
    scheme: "https"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://${DB_DEFAULT_HOST:localhost}:5432/coding_challenge
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      username: coding_challenge_usr
      password: coding_challeng_password

  liquibase:
    change-log: db.changelog/dbchangelog.xml

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 1
          jobStore:
            dataSource: quartzDataSource
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            #            isClustered: true
            #            clusterCheckinInterval: 5000
            tablePrefix: quartz.QRTZ_
    jdbc:
      initialize-schema: never

management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: never
      show-components: never

springdoc:
  show-actuator: false

schedule:
  intervalMinutes: 30
