spring:
  application:
    name: "codingchallenge"
    baseUrl: "www.example.com"
    scheme: "https"
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://${DB_DEFAULT_HOST:localhost}:${DB_DEFAULT_PORT:5432}/coding_challenge
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      username: ${DB_USER:coding_challenge_usr}
      password: ${DB_PASS:coding_challeng_password}

  liquibase:
    change-log: db.changelog/dbchangelog.xml
  cache:
    type: redis
  redis:
    port: ${REDIS_PORT:6379}

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 1
          jobStore:
            dataSource: quartzDataSource
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: quartz.QRTZ_
    jdbc:
      initialize-schema: never

http:
  auth:
    api-key: 901f7b1c-260f-4050-839d-b0cd91a00b9a

client:
  connectionTimeoutMilliseconds: 20000
  readTimeoutMilliseconds: 20000

management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: never
      show-components: never

springdoc:
  show-actuator: false

schedule:
  intervalMinutes: 30
